#!/usr/bin/env python3

import sys
import cProfile

from cache_search_engine import CacheSearchEngine

eng = CacheSearchEngine()

def search_1000(engine):
    with open('1000_words.txt') as words:
        for word in words:
            engine.search(word.strip(), cli=False)
cProfile.run("search_1000(eng)")
