#!/usr/bin/env python3

import sys
import cProfile

from cache_search_engine import CacheSearchEngine

target = sys.argv[1]

engine = CacheSearchEngine()
# cProfile.run("engine.search_cache(target)")
engine.search(target)
